services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

  mcp-server-qdrant:
    build:
      context: https://github.com/qdrant/mcp-server-qdrant.git
      dockerfile: Dockerfile
    environment:
      - QDRANT_URL=http://qdrant:6333
    ports:
      - 8001:8000
    depends_on:
      - qdrant

  prestart:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - qdrant
    command: bash scripts/prestart.sh
    environment:
      - QDRANT_URL=http://qdrant:6333

configs:
  qdrant_config:
    content: |
      log_level: INFO
