services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - QDRANT_URL=http://qdrant:6333
    command: ["fastapi", "run", "app/api/main.py"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

  prestart:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - qdrant
    command: bash scripts/prestart.sh
    environment:
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=${COLLECTION_NAME}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
configs:
  qdrant_config:
    content: |
      log_level: INFO
